---
version: '2'
services:
  common:
    build: "."
    environment:
      DATABASE_URL: mysql://root:A0b1ty4tEY08KugWDf6x4A@db:3306/app
  app:
    extends:
      service: common
    links:
    - db
    ports:
    - 80:80
    command: "/usr/sbin/apache2ctl -D FOREGROUND"
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: A0b1ty4tEY08KugWDf6x4A

